language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler:
        - gcc
      addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: 
          - g++-4.8
          - gcc-4.8
          - libboost-dev 
          - libboost-system-dev
          - libboost-filesystem-dev 
          - libboost-program-options-dev
          - libboost-thread-dev
          - libssl-dev
          - libdb++-dev
          - libminiupnpc-dev
          - libqrencode-dev
          - wget
          - build-essential 
    
    - os: osx
      osx_image: xcode7.3
      compiler:
        - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install berkeley-db wget gcc miniupnpc qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew linkapps qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools -y; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://miniupnp.free.fr/files/download.php?file=miniupnpc-2.0.tar.gz -O miniupnpc-2.0.tar.gz&&tar -xzvf miniupnpc-2.0.tar.gz&&cd miniupnpc-2.0&&sudo make install&&cd ..; fi
script:
  - qmake "USE_UPNP=1"
  - make
