language: c
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.2

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - qt5-default 
      - qt5-qmake
      - qtbase5-dev-tools
      - qttools5-dev-tools
      - build-essential
      - libboost-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-thread-dev
      - libssl-dev libdb++-dev
      - libminiupnpc-dev
      - libqrencode-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost db48 miniupnpc; fi

script:
  - qmake "USE_UPNP=1"
  - make
