language: c
cache:
  directories:
  - $TRAVIS_BUILD_DIR
  - $HOME
matrix:
  include:
 # - os: linux
 #   dist: trusty
 #   sudo: required
  - os: osx
    osx_image: xcode7.3.1
  #- compiler: clang

#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - qt5-default
#    - qt5-qmake
#    - qtbase5-dev-tools
#    - qttools5-dev-tools
#    - build-essential
#    - libboost-dev
#    - libboost-system-dev
#    - libboost-filesystem-dev
#    - libboost-program-options-dev
#    - libboost-thread-dev
#    - libssl-dev libdb++-dev
#    - libminiupnpc-dev
#    - libqrencode-dev
before_install:
#- sudo xcode-select --switch /Library/Developer/CommandLineTools/
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink boost; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall --ignore-dependencies boost; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install protobuf berkeley-db4 miniupnpc qt; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew linkapps qt5; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link qt5 --force; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link openssl --force; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget 'https://github.com/mavrodev/travis-homebrew-bottle/releases/download/boost-v1.63-cxx11/boost-1.63.0.el_capitan.bottle.1.tar.gz';
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost-1.63.0.el_capitan.bottle.1.tar.gz --force; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then MACOSX_DEPLOYMENT_TARGET=10.11 qmake "RELEASE=1" "USE_UPNP=1" OPENSSL_INCLUDE_PATH=/usr/local/opt/openssl/include OPENSSL_LIB_PATH=/usr/local/opt/openssl/lib BDB_INCLUDE_PATH=/usr/local/opt/berkeley-db4/include BDB_LIB_PATH=/usr/local/opt/berkeley-db4/lib MINIUPNPC_INCLUDE_PATH=/usr/local/opt/miniupnpc/include MINIUPNPC_LIB_PATH=/usr/local/opt/miniupnpc/lib BOOST_INCLUDE_PATH=/usr/local/opt/boost/include BOOST_LIB_PATH=/usr/local/opt/boost/lib&&make&& find $TRAVIS_BUILD_DIR/ -name Mavro-*&&zip -r mavro.zip /Users/travis/build/mavrodev/Mavro/Mavro-qt.app; fi
#OPENSSL_INCLUDE_PATH=/usr/local/opt/openssl/include OPENSSL_LIB_PATH=/usr/local/opt/openssl/lib BOOST_INCLUDE_PATH=/usr/local/Cellar/boost/1.63.0 BOOST_LIB_PATH=/usr/local/Cellar/boost/1.63.0&&make&&mv Mavro-qt mavro-osx-qt; fi
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then qmake "USE_UPNP=1"&&make&&mv Mavro-qt mavro-linux-qt; fi
after_success:
- sh set_tags.sh
#before_deploy:
#  - export RELEASE_PKG_FILE=$(ls mavro.zip)
#  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
#  - git add mavro.zip
deploy:
  provider: releases
  api_key:
    secure: WEzubWFgie/UWa697KuJztzGWMpdHXCudEpWnAli8YSZyZEsVhIglh8mbluq4IQ0yORcDaVOaXAzgFlihaPnkTY40ANxjgTl6A6br/5BxOCzVGvemOnVuvj6x0nPkYqjxfG70K8oEoP9+ozf4zFqFFwn6vfgn47GRH5gujMkJqD+MB1bV+PoTNyKx1vy7NIcC94MTfaEyiwGkr5Wmx8QG2LYTpUgWgKHPVv3JE89G+pFVIV1kNHVpgEC6m5wgB/f3T6lr77XN/lq3PfMqNAB5zgOJZRkkYZ3akk9/a156SQqLV2ZoCkSwW6ICtqgZE6S6zB6q5uqynfspLFGcJJbEXO/2NX9QB+HrAkXa+3srpucFPww5XkwAUBAOp/uKCafItg0dERD8kkaqjkCsKs48u6v50U7Jfa4YBAQ3zF5fp2RcrToa71xB9HRYIIP54ILmVQc2kqCxrM8G6GgFvGPuQ3LJQ1QPv6VJS/Kwl2mWPD6GSeHGqC99kdE4yIri88SbnJjNV5hCtdV7Hi26iT9PBH06olhD8SuvN0A7vzq73kiqwIr1RAdwzRAf8pvxY2KDzrnGzBso1MlylG8MBiv8f0E6TGzXZdY0OBaCAXzKaIkLZCLs2uc21qKHtH1rJiCjCKvQ+VBdWTTxauEhZSjD5ENyWk26NTo7ayJaF/dO2o=
  file: "mavro.zip"
  file_glob: true
  skip_cleanup: true
  on:
    branch: master
    repo: mavrodev/Mavro
    

