language: c
matrix:
  include:
    - os: linux
      sudo: required
      compiler:
        - gcc
    
    - os: osx
      osx_image: xcode7.2
      compiler:
        - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update&&brew install boost db53 wget          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa -y&&sudo apt-get update -qq&&apt-get install qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools build-essential libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev libdb++-dev libminiupnpc-dev libqrencode-dev apt-file wget -y; fi
  - wget http://miniupnp.free.fr/files/download.php?file=miniupnpc-2.0.tar.gz&&tar -xzvf miniupnpc-2.0.tar.gz&&cd miniupnpc-2.0&&make&&sudo make install

script:
  - qmake -qt=qt5 "USE_UPNP=1"
  - make
